#!/usr/bin/env python
# ------------------------------------------------------------------------------
# Project : TrueColors                                             /          \
# Filename: truecolors                                            |     ()     |
# Date    : 01/03/2024                                            |            |
# Author  : cyclopticnerve                                        |   \____/   |
# License : WTFPLv2                                                \          /
# ------------------------------------------------------------------------------

"""
docstring
"""

# ------------------------------------------------------------------------------
# Imports
# ------------------------------------------------------------------------------
from pathlib import Path
import re
import shlex
import subprocess

# TODO: on stop service, delete files and call
# 'flatpak override --user --nofilesystem=xdg-config/gtk-4.0'

# TODO: put this in readme:
#!/bin/sh
# echo "Uninstalling ..."
# systemctl --user stop gesture_improvements_gesture_daemon.service
# rm -v ~/.config/systemd/user/gesture_improvements_gesture_daemon.service
# rm -v ~/.local/bin/gesture_improvements_gesture_daemon
# echo "Uninstalled ..."

# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------
DICT_COLORS = {
    "Yaru": [
        "#ed754b",
        "#e95420",
    ],
    "Yaru-bark": [
        "#9a9a77",
        "#787859",
    ],
    "Yaru-sage": [
        "#889d8c",
        "#657b69",
    ],
    "Yaru-olive": [
        "#60aa01",
        "#4b8501",
    ],
    "Yaru-viridian": [
        "#04ad75",
        "#03875b",
    ],
    "Yaru-prussiangreen": [
        "#3ea7a4",
        "#308280",
    ],
    "Yaru-blue": [
        "#369bff",
        "#0073e5",
    ],
    "Yaru-purple": [
        "#9b8de2",
        "#7764d8",
    ],
    "Yaru-magenta": [
        "#c87ec8",
        "#b34cb3",
    ],
    "Yaru-red": [
        "#e67588",
        "#da3450",
    ],
}


# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
def main():
    """
    docstring
    """

    init()
    run()


# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
def init():
    """
    docstring
    """

    cmd = "flatpak --user override --filesystem=xdg-config/gtk-4.0:ro"
    cmd_array = shlex.split(cmd)
    subprocess.run(cmd_array, check=True)

    cmd = "gsettings get org.gnome.desktop.interface gtk-theme"
    cmd_array = shlex.split(cmd)
    result = subprocess.run(
        cmd_array, capture_output=True, text=True, check=True
    )
    write_theme(result.stdout)


# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
def run():
    """
    docstring
    """

    cmd = "gsettings monitor org.gnome.desktop.interface gtk-theme"
    cmd_array = shlex.split(cmd)
    proc = subprocess.Popen(
        cmd_array, stdout=subprocess.PIPE, universal_newlines=True
    )

    if proc and proc.stdout:
        for line in iter(proc.stdout.readline, ""):
            write_theme(line)


# ------------------------------------------------------------------------------
#
# ------------------------------------------------------------------------------
def write_theme(theme_name):
    """
    docstring
    """

    pattern = r"(gtk-theme: )?\'(.*?)(-dark|\')"
    res = re.search(pattern, theme_name)
    if res:
        theme_name = res.group(2)

    if not theme_name in DICT_COLORS:
        return

    accent_color = DICT_COLORS[theme_name][0]
    accent_bg_color = DICT_COLORS[theme_name][1]

    file = Path(Path.home() / ".config/gtk-4.0/gtk.css")
    file.parent.mkdir(exist_ok=True, parents=True)
    file.write_text(
        f"@define-color accent_color {accent_color};\n"
        f"@define-color accent_bg_color {accent_bg_color};\n",
        "utf8"
    )


# ------------------------------------------------------------------------------
# Code to run when called from command line
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    # Code to run when called from command line

    # This is the top level code of the program, called when the Python file is
    # invoked from the command line.

    # run main function
    main()

# -)
